---
version: '3.8'
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SERVERURL=auto #optional
      - SERVERPORT=51820 #optional
      - PEERS=myPhone,myPC #optional List of users
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS=all #optional
      - LOG_CONFS=true #optional
    volumes:
      - /home/pi/IOTstack/volumes/wireguard:/config
      - /lib/modules:/lib/modules:ro
    ports:
     - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped


  wireguard_exporter:
    image: mindflavor/prometheus-wireguard-exporter:latest
    container_name: wireguard_exporter
    command:
      - --prepend_sudo=true 
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard  
    restart: unless-stopped
    depends_on: 
      - wireguard

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    depends_on:
      - wireguard

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - 9080:9080
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail-config.yaml
    command:
      -config.expand-env=true
      -config.file=/etc/promtail-config.yaml
    privileged: true
    depends_on:
      - wireguard
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    depends_on:
      - wireguard

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472"  # UID графаны внутри контейнера
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    depends_on:
      - wireguard


volumes:
  grafana-storage:
  prometheus-storage: